SCREENWIDTH = 800
SCREENHEIGHT = 400
FPS = 10
CELLSIZE = 20
assert SCREENHEIGHT % CELLSIZE == 0
assert SCREENHEIGHT % CELLSIZE == 0
MATRIX_W = int(SCREENWIDTH / CELLSIZE)
MATRIX_H = int (SCREENHEIGHT / CELLSIZE)
MATRIX = MATRIX_W * MATRIX_H
BG_COLOR = (0, 0, 0)
HEAD_INDEX = 0
SPACE_NUM = (MATRIX_H + 1) * (MATRIX_W + 1)
SNAKE_NUM = 2 * SPACE_NUM
FOODNUM = 0
